version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "Newtonsoft.Json"
      - dependency-name: "Bannerlord.ReferenceAssemblies.*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
