name: Check if newer version is available

on:
  schedule:
    - cron:  "10 */1 * * *"
    
jobs:
  check-for-newer-version:
    name: Check for newer version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.300
      env:
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        
    - name: Run VersionChecker (Release)
      id: status
      run: >-
        dotnet build ./build/VersionChecker/VersionChecker.csproj --configuration Release;
        $status = dotnet run --project ./build/VersionChecker/VersionChecker.csproj --no-build --configuration Release ;
        echo "::set-env name=has_newer_version::$status";
      env:
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      shell: pwsh
      
    - name: Log env var
      run:  echo "::warning ::has_newer_version=${{steps.status.outputs.has_newer_version}}"
      
    - name: Trigger publish-on-nexusmods
      if: ${{steps.status.outputs.has_newer_version}} == 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{secrets.REPO_ACCESS_TOKEN}}
        repository: BUTR/Bannerlord.Harmony
        event-type: publish-on-nexusmods
        client-payload: '{"github": ${{ toJson(github) }}}'
