name: Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'src/Bannerlord.Harmony/**'
  repository_dispatch:
    types: publish-on-nexusmods

jobs:
  build-module:
    name: Build for NexusMods
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.x
      env:
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Setup BUTR GPR
      uses: actions/setup-dotnet@master
      with:
        source-url: https://nuget.pkg.github.com/BUTR/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Build Bannerlord.Harmony (Release)
      run: >-
        dotnet build src/Bannerlord.Harmony/Bannerlord.Harmony.csproj --configuration Release -p:GameFolder="$PWD/bannerlord";
      env:
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      shell: pwsh

    - name: Upload Bannerlord folder
      uses: actions/upload-artifact@v2
      with:
        name: bannerlord
        path: ./bannerlord/

###########################
#          NEXUS          #
###########################
  publish-on-nexusmods:
    name: Publish on NexusMods
    needs: ["build-module"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.x
      env:
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Setup BUTR GPR
      uses: actions/setup-dotnet@master
      with:
        source-url: https://nuget.pkg.github.com/BUTR/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Download bannerlord folder
      uses: actions/download-artifact@v2
      with:
        name: bannerlord
        path: ./bannerlord

    - name: Zip Bannerlord.Harmony
      run: 7z a -tzip Bannerlord.Harmony.zip ./bannerlord/*
      shell: pwsh

    - name: Install Bannerlord.NexusmodsUploader
      run: >-
        dotnet tool install -g Bannerlord.NexusmodsUploader;
      env:
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      shell: pwsh

    - name: Get Bannerlord.Harmony version
      id: version
      run: >-
        $vers =(Get-Item './bannerlord/Modules/Bannerlord.Harmony/bin/Win64_Shipping_Client/Bannerlord.Harmony.dll').VersionInfo.ProductVersion.Split("+")[0];
        echo "::set-output name=mod_version::$vers"
      shell: pwsh

    - name: Start Selenoid
      uses: Xotabu4/selenoid-github-action@v1

    - name: Run NexusmodsUploader
      run: >-
        bannerlord_nexusmods_uploader upload -g mountandblade2bannerlord -m 2006 -n "Harmony"
        -v "v${{steps.version.outputs.mod_version}}" -l true -e true -d ""
        -p "$PWD/Bannerlord.Harmony.zip";
      env:
        NEXUSMODS_COOKIES_JSON: '${{secrets.NEXUSMODS_COOKIES_JSON}}'
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      shell: pwsh

    - name: Password protect Screenshots
      run: 7z a -p${{secrets.SCREENSHOTS_PASSWORD}} Screenshots.7z ./Screenshots/*
      shell: pwsh

    - name: Upload Screenshots Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Screenshots
        path: Screenshots.7z

###########################
#         GITHUB          #
###########################
  publish-on-github:
    name: Publish on GitHub
    runs-on: ubuntu-latest
    needs: ["build-module"]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.x
      env:
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Setup BUTR GPR
      uses: actions/setup-dotnet@master
      with:
        source-url: https://nuget.pkg.github.com/BUTR/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Download bannerlord folder
      uses: actions/download-artifact@v2
      with:
        name: bannerlord
        path: ./bannerlord

    - name: Zip Bannerlord.Harmony
      run: 7z a -tzip Bannerlord.Harmony.zip ./bannerlord/*
      shell: pwsh

    - name: Install Bannerlord.NexusmodsUploader
      run: >-
        dotnet tool install -g Bannerlord.NexusmodsUploader;
      env:
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      shell: pwsh

    - name: Get Bannerlord.Harmony version
      id: version
      run: >-
        $vers =(Get-Item './bannerlord/Modules/Bannerlord.Harmony/bin/Win64_Shipping_Client/Bannerlord.Harmony.dll').VersionInfo.ProductVersion.Split("+")[0];
        echo "::set-output name=mod_version::$vers"
      shell: pwsh

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        tag_name: v${{steps.version.outputs.mod_version}}
        release_name: Release ${{steps.version.outputs.mod_version}}
        body: ""
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{steps.create_release.outputs.upload_url}}
        asset_path: ./Bannerlord.Harmony.zip
        asset_name: Bannerlord.Harmony.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}